### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ndebono1** [Protea-Glycosciences/GlyCombo#1]
Please find log attached below:

PLATFORM VERSION INFO
	Windows 			: 10.0.19045.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.9195.0 built by: NET481REL1LAST_B
	clr.dll 			: 4.8.9241.0 built by: NET481REL1LAST_C
	dfdll.dll 			: 4.8.9195.0 built by: NET481REL1LAST_B
	dfshim.dll 			: 10.0.19041.30000 (WinBuild.160101.0800)

SOURCES
	Deployment url			: https://raw.githubusercontent.com/Protea-Glycosciences/GlyCombo/master/published/GlyCombo.application
	Deployment Provider url		: https://raw.githubusercontent.com/Protea-Glycosciences/GlyCombo/master/published/GlyCombo.application
	Application url			: https://raw.githubusercontent.com/Protea-Glycosciences/GlyCombo/master/published/Application%20Files/GlyCombo_0_4_0_1/GlyCombo.dll.manifest

IDENTITIES
	Deployment Identity		: GlyCombo.application, Version=0.4.0.1, Culture=neutral, PublicKeyToken=c255d772058593a1, processorArchitecture=msil
	Application Identity		: GlyCombo.exe, Version=0.4.0.1, Culture=neutral, PublicKeyToken=c255d772058593a1, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://raw.githubusercontent.com/Protea-Glycosciences/GlyCombo/master/published/GlyCombo.application resulted in exception. Following failure messages were detected:
		+ Activation failed.
		+ Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [30/05/2024 8:48:43 AM] : Activation of https://raw.githubusercontent.com/Protea-Glycosciences/GlyCombo/master/published/GlyCombo.application has started.
	* [30/05/2024 8:48:44 AM] : Processing of deployment manifest has successfully completed.
	* [30/05/2024 8:48:44 AM] : Installation of the application has started.
	* [30/05/2024 8:48:44 AM] : Processing of application manifest has successfully completed.
	* [30/05/2024 8:48:48 AM] : Found compatible runtime version 4.0.30319.
	* [30/05/2024 8:48:48 AM] : Request of trust and detection of platform is complete.
	* [30/05/2024 8:49:04 AM] : Downloading of subscription dependencies is complete.
	* [30/05/2024 8:49:04 AM] : Commit of the downloaded application has started.
	* [30/05/2024 8:49:04 AM] : Installation of application has successfully completed.

ERROR DETAILS
	Following errors were detected during this operation.
	* [30/05/2024 8:49:05 AM] System.Deployment.Application.DeploymentException (Activation)
		- Activation failed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.UnauthorizedAccessException
		- Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [30/05/2024 8:49:04 AM]
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: 310GVPXJ.3VP.application
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: GlyCombo.exe.manifest
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: GlyCombo.exe
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: GlyCombo_Logo_Final.ico
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Launcher.exe.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Launcher.exe
		+ System.Deployment.Internal.Isolation.StoreOperationInstallDeployment
			- Status: Installed
			- HRESULT: 0x0
			- AppId: https://raw.githubusercontent.com/Protea-Glycosciences/GlyCombo/master/published/GlyCombo.application#GlyCombo.application, Version=0.4.0.1, Culture=neutral, PublicKeyToken=c255d772058593a1, processorArchitecture=msil
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x0

**Comment by chrashwood** [comment]
Hi @ndebono1,

Thank you for reporting the issue. Could I please confirm that you ran the setup as administrator, or that you have administrator rights on your computer?

As the first troubleshooting step, could you please right click the installer (GlyCombo_setup.exe) and click on the "Run as administrator" option? 

If you aren't able to run the setup as administrator (or lack the right permissions), we can look at also providing a "portable" executable, with the limitation of it not being auto-updating.

Cheers,
Chris

**Comment by ndebono1** [comment]
Everything was run as administrator. A portable execution would be great thanks

**Comment by chrashwood** [comment]
Thanks @ndebono1. I think it might have to do with installation permissions of your computer. I've tried the installer on an unrelated computer with administrator access and the install procedure was successful.

I've added GlyCombo_Portable to the release and github page (https://github.com/Protea-Glycosciences/GlyCombo/releases/download/v0.4/GlyCombo_Portable.exe). Please let me know how that goes.

Cheers,
Chris

**Comment by ndebono1** [comment]
Thanks for that Chris. It was indeed my IT admin restrictions. The Portable works.

**Comment by chrashwood** [comment]
Excellent, glad the portable version works.
Thanks for using GlyCombo, and please feel free to let us know if you encounter any further issues.
