### ISSUE TITLE
Request not issue

### ISSUE THREAD

**Issue by ndebono1** [Protea-Glycosciences/GlyCombo#2]
When importing multiple files to analyse, multiple results windows pop up which are annoying to close. 

Can this be made into one results window with multiple messages?

![glycombo_request](https://github.com/Protea-Glycosciences/GlyCombo/assets/145509538/9e16a648-103b-476a-8a2d-fa0b70e268ef)

**Comment by chrashwood** [comment]
Thanks for the request! We've incorporated it in our new release, v0.5. [Link](https://github.com/Protea-Glycosciences/GlyCombo/releases/tag/v0.5).
