### ISSUE TITLE
Inadequate handling of different decimal separators

### ISSUE THREAD

**Issue by LoponteHF** [Protea-Glycosciences/GlyCombo#9]
Dear developers,

I live in Brazil and thus my decimals are separated by commas (",") by default. When trying to load an mzML file into GlyCombo, the program closes unexpectedly. When checking the Windows event viewer for programs exceptions, there's the following message:

> Application: GlyCombo.exe
> CoreCLR Version: 8.0.1124.51707
> .NET Version: 8.0.11
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.FormatException: The input string '12973994.0' was not in a correct format.
>    at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
>    at System.Number.ParseDecimal[TChar](ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
>    at System.Decimal.Parse(String s, NumberStyles style)
>    at glycombo.MainWindow.mzMLProcess()
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at glycombo.MainWindow.UploadButton_Click(Object sender, RoutedEventArgs e)
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at GlyCombo.App.Main()

This problem indicates it finds the value '12973994.0' to be in an incorrect format. **Changing the Windows decimal separator to a point fixes the issue and GlyCombo runs normally**, but that is a nuisance not all users will be able to realize and fix by themselves.

**Comment by chrashwood** [comment]
Dear HFLoponte,

Thank you for the report and detailed troubleshooting!

Yes, the issue arises because the mzML format is hardcoded for the decimal point (.) whereas users of countries beyond our testing may expect a decimal comma (,). We believe we have a fix now implemented, could you please test the portable version of GlyCombo linked below to confirm that the program no longer crashes? If this solves the issue for you, we'll push these changes onto the main branch following in-house tests to confirm normal functions aren't impacted.

[GlyCombo.zip](https://github.com/user-attachments/files/17926875/GlyCombo.zip)

Cheers,
Chris

**Comment by LoponteHF** [comment]
This particular issue seems to be resolved with this new version. I'm still getting a crash every now and then... For instance, when I try to open a file without MS2 spectra, it gives me a message window saying so and then the program crashes. Checking the event viewer I get the following error:

> Application: GlyCombo.exe
> CoreCLR Version: 8.0.1124.51707
> .NET Version: 8.0.11
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
>    at glycombo.MainWindow.UploadButton_Click(Object sender, RoutedEventArgs e)
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at GlyCombo.App.Main()

This error is not specific to the version you just provided, as it was also happening before.

**Comment by chrashwood** [comment]
If using the mzML input format, GlyCombo requires MS2 scans with assigned charge states. That requirement is described in the publication but I'll update the error message to be more clear about this. There are a variety of methods to assign these charge states but it is largely vendor dependent in their implementation. From all the vendor raw files we've tested, if there is charge state information in your mzML it should work. If charge states are present in your mzML, I'd appreciate if you could share the file so we could troubleshoot further.

We will be working on providing graceful handling of incompatible input and adding missing charges in our command line interface that's coming soon.

Since we've addressed the different decimal separator issue, I'm going to close this and the fix will be included in the next release. Thanks for using GlyCombo!
